import "./globals.css";
import type { Metadata } from "next";
import { Maven_Pro } from "next/font/google";
import NavBar from "@/components/views/NavBar";
import Footer from "@/components/views/Footer";
import { DineMarketContextProvider } from "@/context/DineMarketContext";
const inter = Maven_Pro({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900", "600", "800"],
});
export const metadata: Metadata = {
  title: "Dine Market",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DineMarketContextProvider>
          <div className="max-w-[1440px] mx-auto px-2 md:px-6">
            <NavBar />
            {children}
            <Footer />
          </div>
        </DineMarketContextProvider>
      </body>
    </html>
  );
}
